-- MySQL Script generated by MySQL Workbench
-- Thu Jun 21 12:50:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Specjalizacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specjalizacja` (
  `idSpecjalizacja` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idSpecjalizacja`))
ENGINE = InnoDB
COMMENT = '\n\n	\n		\n		\n\n';


-- -----------------------------------------------------
-- Table `mydb`.`Oddzial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oddzial` (
  `idOddzial` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  `lokalizacja` VARCHAR(45) NULL,
  PRIMARY KEY (`idOddzial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownicy` (
  `idPracownicy` INT NULL,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `Specjalizacja_idSpecjalizacja` INT NOT NULL,
  `Oddzial_idOddzial` INT NOT NULL,
  PRIMARY KEY (`idPracownicy`, `Specjalizacja_idSpecjalizacja`, `Oddzial_idOddzial`),
  INDEX `fk_Pracownicy_Specjalizacja1_idx` (`Specjalizacja_idSpecjalizacja` ASC),
  INDEX `fk_Pracownicy_Oddzial1_idx` (`Oddzial_idOddzial` ASC),
  CONSTRAINT `fk_Pracownicy_Specjalizacja1`
    FOREIGN KEY (`Specjalizacja_idSpecjalizacja`)
    REFERENCES `mydb`.`Specjalizacja` (`idSpecjalizacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownicy_Oddzial1`
    FOREIGN KEY (`Oddzial_idOddzial`)
    REFERENCES `mydb`.`Oddzial` (`idOddzial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pacjent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacjent` (
  `idPacjent` INT NOT NULL,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(100) NULL,
  `PESEL` VARCHAR(45) NULL,
  `dataPrzyjecia` DATE NULL,
  `dataWypisu` DATE NULL,
  PRIMARY KEY (`idPacjent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RodzajOperacji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RodzajOperacji` (
  `idRodzajOperacji` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  `planowanyCzas` INT NULL,
  `Specjalizacja_idSpecjalizacja` INT NOT NULL,
  PRIMARY KEY (`idRodzajOperacji`, `Specjalizacja_idSpecjalizacja`),
  INDEX `fk_RodzajOperacji_Specjalizacja1_idx` (`Specjalizacja_idSpecjalizacja` ASC),
  CONSTRAINT `fk_RodzajOperacji_Specjalizacja1`
    FOREIGN KEY (`Specjalizacja_idSpecjalizacja`)
    REFERENCES `mydb`.`Specjalizacja` (`idSpecjalizacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SaleOperacyjne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SaleOperacyjne` (
  `idSaleOperacyjne` INT NOT NULL,
  `Oddzial_idOddzial` INT NOT NULL,
  PRIMARY KEY (`idSaleOperacyjne`, `Oddzial_idOddzial`),
  INDEX `fk_SaleOperacyjne_Oddzial1_idx` (`Oddzial_idOddzial` ASC),
  CONSTRAINT `fk_SaleOperacyjne_Oddzial1`
    FOREIGN KEY (`Oddzial_idOddzial`)
    REFERENCES `mydb`.`Oddzial` (`idOddzial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operacja` (
  `idOperacja` INT NOT NULL,
  `terminRozpOperacji` DATETIME NULL,
  `terminZakOper` DATETIME NULL,
  `Pacjent_idPacjent` INT NULL,
  `RodzajOperacji_idRodzajOperacji` INT NULL,
  `SaleOperacyjne_idSaleOperacyjne` INT NULL,
  PRIMARY KEY (`idOperacja`),
  INDEX `fk_Operacja_Pacjent1_idx` (`Pacjent_idPacjent` ASC),
  INDEX `fk_Operacja_RodzajOperacji1_idx` (`RodzajOperacji_idRodzajOperacji` ASC),
  INDEX `fk_Operacja_SaleOperacyjne1_idx` (`SaleOperacyjne_idSaleOperacyjne` ASC),
  CONSTRAINT `fk_Operacja_Pacjent1`
    FOREIGN KEY (`Pacjent_idPacjent`)
    REFERENCES `mydb`.`Pacjent` (`idPacjent`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Operacja_RodzajOperacji1`
    FOREIGN KEY (`RodzajOperacji_idRodzajOperacji`)
    REFERENCES `mydb`.`RodzajOperacji` (`idRodzajOperacji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operacja_SaleOperacyjne1`
    FOREIGN KEY (`SaleOperacyjne_idSaleOperacyjne`)
    REFERENCES `mydb`.`SaleOperacyjne` (`idSaleOperacyjne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SaleOddzialowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SaleOddzialowe` (
  `idSaleOddzialowe` INT NOT NULL,
  `Oddzial_idOddzial` INT NOT NULL,
  PRIMARY KEY (`idSaleOddzialowe`, `Oddzial_idOddzial`),
  INDEX `fk_SaleOddzialowe_Oddzial1_idx` (`Oddzial_idOddzial` ASC),
  CONSTRAINT `fk_SaleOddzialowe_Oddzial1`
    FOREIGN KEY (`Oddzial_idOddzial`)
    REFERENCES `mydb`.`Oddzial` (`idOddzial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lozko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lozko` (
  `idLozko` INT NOT NULL,
  `numer` INT NULL,
  `SaleOddzialowe_idSaleOddzialowe` INT NOT NULL,
  PRIMARY KEY (`idLozko`, `SaleOddzialowe_idSaleOddzialowe`),
  INDEX `fk_Lozko_SaleOddzialowe1_idx` (`SaleOddzialowe_idSaleOddzialowe` ASC),
  CONSTRAINT `fk_Lozko_SaleOddzialowe1`
    FOREIGN KEY (`SaleOddzialowe_idSaleOddzialowe`)
    REFERENCES `mydb`.`SaleOddzialowe` (`idSaleOddzialowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LozkoHistoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LozkoHistoria` (
  `idLozkoHistoria` INT NOT NULL,
  `Lozko_idLozko` INT NULL,
  `Pacjent_idPacjent` INT NULL,
  PRIMARY KEY (`idLozkoHistoria`, `Lozko_idLozko`, `Pacjent_idPacjent`),
  INDEX `fk_LozkoHistoria_Lozko_idx` (`Lozko_idLozko` ASC),
  INDEX `fk_LozkoHistoria_Pacjent1_idx` (`Pacjent_idPacjent` ASC),
  CONSTRAINT `fk_LozkoHistoria_Lozko`
    FOREIGN KEY (`Lozko_idLozko`)
    REFERENCES `mydb`.`Lozko` (`idLozko`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_LozkoHistoria_Pacjent1`
    FOREIGN KEY (`Pacjent_idPacjent`)
    REFERENCES `mydb`.`Pacjent` (`idPacjent`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
